name: Publish Cirrus container

on:
  workflow_dispatch:
  push:
    branches: ['UE5.4']
    paths: ['SignallingWebServer/**']

jobs:
  signalling-server-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: hub.docker.com
          username: pixelstreamingunofficial
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push the Signalling Server container image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: 'hub.docker.com/repositories/pixelstreamingunofficial/pixel-streaming-signalling-server:5.4'
          push: true
          file: SignallingWebServer/Dockerfile
      -
        name: Build and push the SFU container image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: 'ghcr.io/epicgames/pixel-streaming-sfu:5.4'
          push: true
          file: SFU/Dockerfile
          
