name: Run lint tests on Signalling lib

on:
  workflow_dispatch:
  push:
    branches: ['UE5.5']
    paths: ['Signalling/**']
  pull_request:
    branches: ['UE5.5']
    paths: ['Signalling/**']

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Signalling
    steps:
    - name: "Checkout source code"
      uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: '18.17.0'
        registry-url: 'https://registry.npmjs.org'
    - run: npm --version
    - run: node --version
    - run: npm ci
    - run: npm link ../Common
    - run: npm run lint
      
